<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Michael Borck">
<meta name="dcterms.date" content="2026-03-22">
<meta name="keywords" content="ten-pin bowling, scoring systems, combinatorics, skill discrimination, sequence sensitivity, World Bowling, Monte Carlo simulation">

<title>Skill, Sequence, and Scoring: A Mathematical Comparison of Traditional and World Bowling Scoring Systems</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="bowling_paper_files/libs/clipboard/clipboard.min.js"></script>
<script src="bowling_paper_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="bowling_paper_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="bowling_paper_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="bowling_paper_files/libs/quarto-html/popper.min.js"></script>
<script src="bowling_paper_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="bowling_paper_files/libs/quarto-html/anchor.min.js"></script>
<link href="bowling_paper_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="bowling_paper_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="bowling_paper_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="bowling_paper_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="bowling_paper_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="bowling_paper.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Skill, Sequence, and Scoring: A Mathematical Comparison of Traditional and World Bowling Scoring Systems</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Michael Borck <a href="mailto:michael.borck@curtin.edu.au" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Curtin University
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 22, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>Ten-pin bowling’s traditional scoring system rewards sustained performance: strikes and spares earn bonus points from subsequent balls, creating dependencies across frames. World Bowling has promoted a simpler alternative in which each frame is scored independently. But what exactly is lost when these dependencies are removed?</p>
    <p>This paper answers that question in two parts. Part 1 uses exact combinatorial enumeration to prove that World Bowling scoring is mathematically invariant to the order of frames — meaning two players who throw identical frames in different sequences always receive the same score. Traditional scoring, by contrast, produces score differences of up to 39 points from reordering alone. Part 2 uses Monte Carlo simulation across six skill tiers, calibrated against PBA data, to identify a crossover at approximately 50% strike rate: below this, World Bowling provides adequate score spread; above it, traditional scoring provides over 30% more spread, precisely where elite competition requires finer discrimination.</p>
    <p>We do not argue that current-frame scoring lacks merit. For recreational participants, its simplicity is a genuine improvement. Our argument is narrower: at the competitive and professional levels, where the ability to sustain consecutive strikes distinguishes elite performers, current-frame scoring’s independence property actively obscures the performance differences it should be measuring.</p>
  </div>
</div>

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>ten-pin bowling, scoring systems, combinatorics, skill discrimination, sequence sensitivity, World Bowling, Monte Carlo simulation</p>
  </div>
</div>

</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Ten-pin bowling has been scored using the same traditional system for over a century. Under this system, a strike earns ten pins plus the total of the next two balls thrown, and a spare earns ten pins plus the next ball. This forward-looking bonus structure creates scoring dependencies across frames, rewarding sustained performance non-linearly.</p>
<p>World Bowling, the international governing body for the sport, has promoted an alternative current-frame scoring system <span class="citation" data-cites="worldbowling2014">(<a href="#ref-worldbowling2014" role="doc-biblioref">World Bowling, 2014</a>)</span> in which each frame is scored independently: a strike earns 30 points, a spare earns 10 plus the first ball of that frame, and an open frame earns the sum of both balls. The stated motivation is simplicity — spectators and new participants can follow the score without tracking future balls. This push has intensified as the International Bowling Federation pursues Olympic inclusion, where broadcast accessibility is a key selection criterion <span class="citation" data-cites="insidethegames2014">(<a href="#ref-insidethegames2014" role="doc-biblioref">Inside The Games, 2014</a>)</span>, and has culminated in the launch of international franchise competitions using current-frame scoring exclusively <span class="citation" data-cites="reuters2025wbl">(<a href="#ref-reuters2025wbl" role="doc-biblioref">Reuters, 2025</a>)</span>. The question of whether this simplification preserves the competitive properties the sport requires at the elite level is therefore not academic — it is an active governance decision with immediate consequences.</p>
<p>A simple example illustrates the core difference. Consider two players who each throw five strikes and four spares across frames 1–9, followed by an identical frame 10. Under World Bowling, both players score 219 — regardless of whether the strikes were consecutive or scattered throughout the game. Under traditional scoring, the player who placed strikes consecutively scores up to 20 points higher than one who alternated. The same frames, in different order, produce the same World Bowling score but meaningfully different traditional scores. This paper asks: does this distinction matter, and at what skill level does it become competitively significant?</p>
<p>Several informal comparisons of these systems exist online, focusing primarily on average scores and the presence of impossible scores in the World Bowling range. <span class="citation" data-cites="cooper1990">Cooper &amp; Kennedy (<a href="#ref-cooper1990" role="doc-biblioref">1990</a>)</span> provided the foundational mathematical treatment of traditional bowling score distributions using generating functions, later extended by <span class="citation" data-cites="hohn2009">Hohn (<a href="#ref-hohn2009" role="doc-biblioref">2009</a>)</span> to generalised N-frame, M-pin games. <span class="citation" data-cites="keogh2011">Keogh &amp; O’Neill (<a href="#ref-keogh2011" role="doc-biblioref">2011</a>)</span> studied empirical bowling score distributions using real game data. However, no prior work has formally compared the mathematical properties of both scoring systems, characterised sequence sensitivity as a distinguishing property, or quantified the skill level at which scoring system choice becomes competitively significant.</p>
<p>This paper provides that treatment in two complementary parts: exact mathematical analysis (Part 1) and skill-weighted simulation (Part 2).</p>
</section>
<section id="part-1-mathematical-analysis" class="level1 unnumbered">
<h1 class="unnumbered">Part 1: Mathematical Analysis</h1>
</section>
<section id="mathematical-framework" class="level1">
<h1>Mathematical Framework</h1>
<section id="state-space-and-enumeration" class="level2">
<h2 class="anchored" data-anchor-id="state-space-and-enumeration">State Space and Enumeration</h2>
<p>The total number of distinct ten-pin bowling games is finite and well-defined. Under traditional scoring, each of frames 1–9 admits 66 possible throwing outcomes (one strike, plus all combinations of two balls summing to at most 10), and frame 10 admits 241 outcomes (accounting for bonus balls). The total game count is therefore:</p>
<p><span class="math display">\[66^9 \times 241 = 5{,}726{,}805{,}883{,}325{,}784{,}576 \approx 5.7 \times 10^{18}\]</span></p>
<p>Under World Bowling scoring, all ten frames are identical (no bonus ball in frame 10), giving:</p>
<p><span class="math display">\[66^{10} = 1{,}568{,}336{,}880{,}910{,}795{,}776 \approx 1.6 \times 10^{18}\]</span></p>
<p>Direct enumeration of these game spaces is computationally infeasible, and the resulting distributions are highly multimodal and non-normal — as demonstrated empirically by <span class="citation" data-cites="mccarthy2011">McCarthy (<a href="#ref-mccarthy2011" role="doc-biblioref">2011</a>)</span> using PBA tournament data — ruling out simple parametric approximations. We therefore employ dynamic programming with state representation tracking pending bonus multipliers, following the convolution approach described by <span class="citation" data-cites="balmoral">Balmoral Software (<a href="#ref-balmoral" role="doc-biblioref">2019</a>)</span>. The key insight is that the score contribution of each ball depends only on the current pending bonus state — not on the full history of prior balls — allowing the computation to proceed frame by frame with a manageable number of distinct states (on the order of hundreds of thousands, rather than quintillions of complete games). Our independent implementation produces results that match their published tables exactly at every verification point, including the mode of 77 for traditional scoring with 172,542,309,343,731,946 possible games, and the mode of 72 for World Bowling scoring with 43,781,414,679,391,290 possible games.</p>
</section>
<section id="scoring-functions" class="level2">
<h2 class="anchored" data-anchor-id="scoring-functions">Scoring Functions</h2>
<p><strong>Traditional scoring:</strong> For frames 1–9, let <span class="math inline">\(A_i\)</span> and <span class="math inline">\(B_i\)</span> denote the first and second balls of frame <span class="math inline">\(i\)</span>. For a strike (<span class="math inline">\(A_i = 10\)</span>), the frame score is <span class="math inline">\(10 + A_{i+1} + B_{i+1}\)</span>. For a spare (<span class="math inline">\(A_i + B_i = 10\)</span>), the frame score is <span class="math inline">\(10 + A_{i+1}\)</span>. Otherwise the frame score is <span class="math inline">\(A_i + B_i\)</span>. Frame 10 follows special rules permitting up to three balls with no bonus propagation beyond the frame.</p>
<p><strong>World Bowling scoring:</strong> For each frame <span class="math inline">\(i\)</span>, the score is: 30 (strike), <span class="math inline">\(10 + A_i\)</span> (spare), or <span class="math inline">\(A_i + B_i\)</span> (open). All ten frames are scored identically; no inter-frame dependencies exist.</p>
</section>
</section>
<section id="score-distributions" class="level1">
<h1>Score Distributions</h1>
<section id="summary-statistics" class="level2">
<h2 class="anchored" data-anchor-id="summary-statistics">Summary Statistics</h2>
<div id="tbl-summary" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Summary statistics for exact score distributions under uniform random play.
</figcaption>
<div aria-describedby="tbl-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Statistic</th>
<th>Traditional</th>
<th>World Bowling</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Total games</td>
<td><span class="math inline">\(5.73 \times 10^{18}\)</span></td>
<td><span class="math inline">\(1.57 \times 10^{18}\)</span></td>
</tr>
<tr class="even">
<td>Score range</td>
<td>0–300</td>
<td>0–289, 300</td>
</tr>
<tr class="odd">
<td>Mode</td>
<td>77</td>
<td>72</td>
</tr>
<tr class="even">
<td>Mean</td>
<td>79.7</td>
<td>76.5</td>
</tr>
<tr class="odd">
<td>Median</td>
<td>79</td>
<td>75</td>
</tr>
<tr class="even">
<td>Standard deviation</td>
<td>13.7</td>
<td>15.2</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-distribution" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-distribution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<embed src="../figures/fig1_distribution_overlay.pdf" class="img-fluid" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-distribution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Score distributions under traditional and World Bowling scoring, computed by exact combinatorial enumeration over all possible games. Dashed lines indicate modes.
</figcaption>
</figure>
</div>
</section>
<section id="impossible-scores" class="level2">
<h2 class="anchored" data-anchor-id="impossible-scores">Impossible Scores</h2>
<p>A structural property of World Bowling scoring is the impossibility of scores in the range 290–299. This arises because 9 strikes yield at most <span class="math inline">\(9 \times 30 + 19 = 289\)</span> (9 strikes plus one maximum spare of 10 + 9), while 10 strikes yield exactly 300. No sequence of legal balls can produce a game score between 290 and 299 inclusive under World Bowling rules. This gap is not a curiosity — it is a direct consequence of the linear, frame-independent scoring structure, and it reveals a fundamental property: <strong>the score space is not fully utilised</strong>.</p>
<div id="fig-tail" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tail-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<embed src="../figures/fig2_high_score_tail.pdf" class="img-fluid" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tail-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: High-score tail on log scale. The shaded region at 290–299 marks scores that are mathematically impossible under World Bowling.
</figcaption>
</figure>
</div>
</section>
<section id="high-score-compression" class="level2">
<h2 class="anchored" data-anchor-id="high-score-compression">High-Score Compression</h2>
<p>The number of distinct game sequences producing each high score differs markedly between systems:</p>
<div id="tbl-compression" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-compression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Number of distinct game sequences producing each high score.
</figcaption>
<div aria-describedby="tbl-compression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Score</th>
<th>Traditional</th>
<th>World Bowling</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>200</td>
<td>1,526,313,637</td>
<td>7,019,752,752</td>
</tr>
<tr class="even">
<td>240</td>
<td>335,065</td>
<td>1,599,447</td>
</tr>
<tr class="odd">
<td>260</td>
<td>3,534</td>
<td>9,225</td>
</tr>
<tr class="even">
<td>280</td>
<td>26</td>
<td>10</td>
</tr>
<tr class="odd">
<td>290</td>
<td>11</td>
<td>0 (impossible)</td>
</tr>
<tr class="even">
<td>300</td>
<td>1</td>
<td>1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>At scores of 200 and above, World Bowling consistently offers more paths to the same score. This score compression means that at competitive levels, where players regularly score above 200, the scoring system provides less discrimination between players of different ability.</p>
</section>
</section>
<section id="sequence-sensitivity" class="level1">
<h1>Sequence Sensitivity</h1>
<section id="commutativity-of-world-bowling-scoring" class="level2">
<h2 class="anchored" data-anchor-id="commutativity-of-world-bowling-scoring">Commutativity of World Bowling Scoring</h2>
<p><strong>Proposition 1.</strong> <em>Under World Bowling scoring, the total game score is invariant under any permutation of the ten frames.</em></p>
<p><em>Proof.</em> Let <span class="math inline">\(f_i\)</span> denote the score of frame <span class="math inline">\(i\)</span> under World Bowling rules. The total game score is <span class="math inline">\(S = \sum_{i=1}^{10} f_i\)</span>. Since each <span class="math inline">\(f_i\)</span> is computed from balls thrown within frame <span class="math inline">\(i\)</span> alone, and addition is commutative and associative, any permutation <span class="math inline">\(\sigma\)</span> of the frames yields <span class="math inline">\(S' = \sum_{i=1}^{10} f_{\sigma(i)} = S\)</span>. <span class="math inline">\(\square\)</span></p>
<p>This property — commutativity with respect to frame order — does not hold for traditional scoring. Under traditional scoring, a strike in frame <span class="math inline">\(i\)</span> depends on balls thrown in frames <span class="math inline">\(i+1\)</span> and potentially <span class="math inline">\(i+2\)</span>. Reordering frames changes which balls serve as bonuses, and therefore changes the score.</p>
</section>
<section id="empirical-demonstration" class="level2">
<h2 class="anchored" data-anchor-id="empirical-demonstration">Empirical Demonstration</h2>
<p>We compute scores for fixed frame compositions under varying orderings. Consider 9 frames comprising 5 strikes and 4 spares (5,5) in various orderings, followed by a neutral frame 10 (5, 4):</p>
<div id="tbl-sequence" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sequence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Scores for four orderings of the same frame composition (5 strikes + 4 spares).
</figcaption>
<div aria-describedby="tbl-sequence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Sequence (9 frames + neutral 10th)</th>
<th>Traditional</th>
<th>World Bowling</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>5 strikes then 4 spares</td>
<td>204</td>
<td>219</td>
</tr>
<tr class="even">
<td>Alternating: strike, spare × 4, strike</td>
<td>188</td>
<td>219</td>
</tr>
<tr class="odd">
<td>4 spares then 5 strikes</td>
<td>208</td>
<td>219</td>
</tr>
<tr class="even">
<td>X, sp, sp, X, sp, X, X, sp, X</td>
<td>188</td>
<td>219</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Under World Bowling, all four orderings score identically (219). Under traditional scoring, the score varies by 20 points (188–208) depending solely on the ordering.</p>
<div id="fig-sequence" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sequence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<embed src="../figures/fig5_sequence_sensitivity.pdf" class="img-fluid" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sequence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Sequence sensitivity across three compositions (2, 5, and 7 strikes out of 9 frames). In each panel, the same frames are reordered. World Bowling scores are identical for all orderings; traditional scores vary, with the range increasing at higher strike counts.
</figcaption>
</figure>
</div>
</section>
<section id="exhaustive-permutation-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exhaustive-permutation-analysis">Exhaustive Permutation Analysis</h2>
<p>To quantify the full extent of sequence sensitivity, we enumerate all distinct permutations of fixed frame compositions and compute the score under each system. For compositions of <span class="math inline">\(k\)</span> strikes and <span class="math inline">\((9-k)\)</span> spares in frames 1–9:</p>
<div id="tbl-permutations" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-permutations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Exhaustive permutation analysis. Traditional score range and standard deviation grow with the mix of frame types; World Bowling range is exactly zero for every composition.
</figcaption>
<div aria-describedby="tbl-permutations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Composition</th>
<th>Orderings</th>
<th>Trad. range</th>
<th>Trad. SD</th>
<th>WB range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1 strike + 8 spares</td>
<td>9</td>
<td>5</td>
<td>1.7</td>
<td>0</td>
</tr>
<tr class="even">
<td>2 strikes + 7 spares</td>
<td>36</td>
<td>6</td>
<td>2.1</td>
<td>0</td>
</tr>
<tr class="odd">
<td>3 strikes + 6 spares</td>
<td>84</td>
<td>11</td>
<td>2.9</td>
<td>0</td>
</tr>
<tr class="even">
<td>4 strikes + 5 spares</td>
<td>126</td>
<td>16</td>
<td>4.2</td>
<td>0</td>
</tr>
<tr class="odd">
<td>5 strikes + 4 spares</td>
<td>126</td>
<td>21</td>
<td>5.5</td>
<td>0</td>
</tr>
<tr class="even">
<td>6 strikes + 3 spares</td>
<td>84</td>
<td>26</td>
<td>6.4</td>
<td>0</td>
</tr>
<tr class="odd">
<td>7 strikes + 2 spares</td>
<td>36</td>
<td>26</td>
<td>6.6</td>
<td>0</td>
</tr>
<tr class="even">
<td>8 strikes + 1 spare</td>
<td>9</td>
<td>15</td>
<td>5.6</td>
<td>0</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The World Bowling score range is exactly zero for every composition — confirming Proposition 1 empirically. The traditional score range grows with the mix of frame types, peaking at 26 points for compositions with 6–7 strikes. When open frames are included alongside strikes, the range increases further: 5 strikes mixed with 4 open frames (5, 4) produces a 39-point range across 126 orderings.</p>
<div id="fig-permvar" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-permvar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<embed src="../figures/fig6_permutation_variance.pdf" class="img-fluid" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-permvar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Left: score range across all orderings by composition. Right: score standard deviation due to frame order alone. World Bowling is zero throughout.
</figcaption>
</figure>
</div>
<div id="fig-permdist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-permdist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<embed src="../figures/fig7_permutation_distribution.pdf" class="img-fluid" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-permdist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Score distribution across all orderings for three compositions (2, 5, and 7 strikes). Traditional scores spread across a range that widens with strike count; World Bowling collapses to a single value (dashed line) in every case.
</figcaption>
</figure>
</div>
</section>
<section id="implications-for-skill" class="level2">
<h2 class="anchored" data-anchor-id="implications-for-skill">Implications for Skill</h2>
<p>Sequence sensitivity has a direct sporting interpretation. In competitive bowling, a player who strings consecutive strikes together is demonstrating a qualitatively different level of performance than one who scatters the same number of strikes throughout a game. The traditional scoring system encodes this distinction numerically. The World Bowling system does not.</p>
<p>The maximum score achievable with a fixed number of strikes is higher when those strikes are consecutive (due to compounding bonuses from subsequent strikes), creating a score incentive for sustained excellence. Under World Bowling, a bowler who throws five consecutive strikes in frames 1–5 and then opens all remaining frames achieves the same score as one who alternates strikes and open frames — regardless of how much more difficult the sustained streak was to achieve.</p>
</section>
</section>
<section id="the-reward-gradient-for-consecutive-strikes" class="level1">
<h1>The Reward Gradient for Consecutive Strikes</h1>
<p>We define the <strong>marginal strike value</strong> as the increase in game score when one additional open frame (5, 4) is replaced by a strike, all other frames remaining constant. Under World Bowling this value is trivially constant: <span class="math inline">\(30 - 9 = 21\)</span> points per strike added.</p>
<p>Under traditional scoring, the marginal value depends on the surrounding context:</p>
<div id="tbl-gradient" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-gradient-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Marginal value of each additional consecutive strike.
</figcaption>
<div aria-describedby="tbl-gradient-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Consecutive strikes</th>
<th>Trad. Score</th>
<th>World Score</th>
<th>Trad. Marginal</th>
<th>World Marginal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>90</td>
<td>90</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="even">
<td>1</td>
<td>100</td>
<td>111</td>
<td>+10</td>
<td>+21</td>
</tr>
<tr class="odd">
<td>2</td>
<td>116</td>
<td>132</td>
<td>+16</td>
<td>+21</td>
</tr>
<tr class="even">
<td>3</td>
<td>137</td>
<td>153</td>
<td>+21</td>
<td>+21</td>
</tr>
<tr class="odd">
<td>4</td>
<td>158</td>
<td>174</td>
<td>+21</td>
<td>+21</td>
</tr>
<tr class="even">
<td>5</td>
<td>179</td>
<td>195</td>
<td>+21</td>
<td>+21</td>
</tr>
<tr class="odd">
<td>10</td>
<td>300</td>
<td>300</td>
<td>+37</td>
<td>+21</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Two observations are immediate. First, the initial strikes are undervalued in traditional scoring relative to World Bowling — the first strike adds only 10 points compared to 21 under World Bowling. This is because the bonus from a lone strike depends on subsequent balls that are in this model open frames (5, 4 = 9 pins), capping the bonus at 9. Second, the final strike in a perfect game is worth 37 points under traditional scoring — substantially more than World Bowling’s flat 21 — because it is preceded by two strikes that each earn its bonus retroactively.</p>
<p>This structure rewards the <em>completion</em> of a skill streak more than its initiation. The first strike of a sequence is worth relatively little; the strike that extends a string is worth substantially more. Under World Bowling, every strike is worth exactly the same regardless of what surrounds it.</p>
<div id="fig-gradient" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gradient-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<embed src="../figures/fig3_reward_gradient.pdf" class="img-fluid" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gradient-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Marginal value of each additional consecutive strike, shown for three different non-strike fill patterns: weak (3,2), mid (5,4), and strong (8,1). The compounding pattern in traditional scoring and the flat World Bowling marginal are structural, not dependent on the fill choice.
</figcaption>
</figure>
</div>
</section>
<section id="part-2-skill-weighted-simulation" class="level1 unnumbered">
<h1 class="unnumbered">Part 2: Skill-Weighted Simulation</h1>
</section>
<section id="simulation-model" class="level1">
<h1>Simulation Model</h1>
<section id="player-model" class="level2">
<h2 class="anchored" data-anchor-id="player-model">Player Model</h2>
<p>To ground the mathematical analysis in realistic playing conditions, we simulate bowling games across six empirically motivated skill tiers. Each player is characterised by three parameters: strike probability (<span class="math inline">\(p_s\)</span>), spare conversion probability (<span class="math inline">\(p_{sp}\)</span>), and mean first-ball pin count when not striking.</p>
<div id="tbl-tiers" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tiers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Skill tier parameters. The recreational tier targets casual once-a-month bowlers (USBC league averages); the professional tier targets the PBA Tour season average of approximately 230; the Top 10 tier approximates the elite end of PBA performance <span class="citation" data-cites="yaari2012">(<a href="#ref-yaari2012" role="doc-biblioref">Yaari &amp; Eisenmann, 2012</a>)</span>.
</figcaption>
<div aria-describedby="tbl-tiers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Skill Tier</th>
<th>Strike Rate</th>
<th>Spare Rate</th>
<th>Pin Mean</th>
<th>Target Trad. Mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Recreational</td>
<td>4%</td>
<td>27%</td>
<td>4.2</td>
<td>~90</td>
</tr>
<tr class="even">
<td>Club</td>
<td>20%</td>
<td>47%</td>
<td>5.5</td>
<td>~130</td>
</tr>
<tr class="odd">
<td>Competitive</td>
<td>40%</td>
<td>64%</td>
<td>6.5</td>
<td>~175</td>
</tr>
<tr class="even">
<td>Elite</td>
<td>55%</td>
<td>77%</td>
<td>7.2</td>
<td>~210</td>
</tr>
<tr class="odd">
<td>Professional</td>
<td>66%</td>
<td>86%</td>
<td>7.8</td>
<td>~230</td>
</tr>
<tr class="even">
<td>Top 10</td>
<td>73%</td>
<td>92%</td>
<td>8.2</td>
<td>~245</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="simulation-protocol" class="level2">
<h2 class="anchored" data-anchor-id="simulation-protocol">Simulation Protocol</h2>
<p>We employ three progressively realistic simulation models to ensure robustness of results:</p>
<ol type="1">
<li><p><strong>Independent model (base case).</strong> Each ball is generated independently: the first ball of each frame is a strike with probability <span class="math inline">\(p_s\)</span>, otherwise pins follow a binomial distribution; the second ball converts the spare with flat probability <span class="math inline">\(p_{sp}\)</span>.</p></li>
<li><p><strong>Momentum model.</strong> Strike probability increases by 5 percentage points after a strike and decreases after an open frame, capturing the simplest form of sequential dependence.</p></li>
<li><p><strong>Markov chain model with spare difficulty.</strong> Strike probability follows a first-order Markov chain with state-dependent transition probabilities informed by the empirical hot-hand magnitudes reported in <span class="citation" data-cites="vanderwerken2018">VanDerwerken &amp; Kenter (<a href="#ref-vanderwerken2018" role="doc-biblioref">2018</a>)</span>, who built on the streak probability framework of <span class="citation" data-cites="martin2006">Martin (<a href="#ref-martin2006" role="doc-biblioref">2006</a>)</span> to fit 4th-order Markov models to 26,102 PBA tournament games from 53 professional bowlers. Their posterior estimates show strike probability increasing by approximately 5–10 percentage points after consecutive strikes relative to a cold state. We apply conservative first-order transition ratios: <span class="math inline">\(P(\text{strike} \mid \text{prev. strike}) = p_s \times 1.15\)</span>, <span class="math inline">\(P(\text{strike} \mid \text{prev. spare}) = p_s \times 0.95\)</span>, <span class="math inline">\(P(\text{strike} \mid \text{prev. open}) = p_s \times 0.85\)</span>. Spare conversion is leave-dependent, with three difficulty classes consistent with the non-strike leave distributions reported in <span class="citation" data-cites="vanderwerken2018">VanDerwerken &amp; Kenter (<a href="#ref-vanderwerken2018" role="doc-biblioref">2018</a>)</span> Tables 7–8: easy single-pin leaves (55% of non-strike results, high conversion), moderate multi-pin leaves (35%, baseline conversion), and splits (10%, conversion rate reduced to 30% of baseline).</p></li>
</ol>
<p>For each skill tier, we simulate 50,000 complete games under each model. Every simulated game is scored under both traditional and World Bowling rules, enabling paired comparison. The independent model provides a conservative lower bound; the Markov model provides the most realistic estimate.</p>
</section>
<section id="tier-results" class="level2">
<h2 class="anchored" data-anchor-id="tier-results">Tier Results</h2>
<div id="tbl-tierresults" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tierresults-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Simulated score statistics by skill tier (50,000 games each).
</figcaption>
<div aria-describedby="tbl-tierresults-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Skill Tier</th>
<th>Traditional Mean (SD)</th>
<th>World Bowling Mean (SD)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Recreational</td>
<td>91 (14.2)</td>
<td>95 (17.7)</td>
</tr>
<tr class="even">
<td>Club</td>
<td>133 (21.2)</td>
<td>149 (26.8)</td>
</tr>
<tr class="odd">
<td>Competitive</td>
<td>176 (25.8)</td>
<td>200 (28.1)</td>
</tr>
<tr class="even">
<td>Elite</td>
<td>209 (26.6)</td>
<td>233 (25.1)</td>
</tr>
<tr class="odd">
<td>Professional</td>
<td>232 (25.7)</td>
<td>253 (21.4)</td>
</tr>
<tr class="even">
<td>Top 10</td>
<td>246 (24.4)</td>
<td>265 (18.6)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-tierdist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tierdist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<embed src="../figures/fig8_tier_distributions.pdf" class="img-fluid" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tierdist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Score distributions at each skill tier under both scoring systems.
</figcaption>
</figure>
</div>
<div id="fig-tiermeans" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tiermeans-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<embed src="../figures/fig9_mean_scores_tiers.pdf" class="img-fluid" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tiermeans-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Left: mean scores by skill tier. Right: score standard deviation — note the crossover between systems.
</figcaption>
</figure>
</div>
</section>
</section>
<section id="the-score-spread-crossover" class="level1">
<h1>The Score Spread Crossover</h1>
<section id="standard-deviation-as-a-function-of-skill" class="level2">
<h2 class="anchored" data-anchor-id="standard-deviation-as-a-function-of-skill">Standard Deviation as a Function of Skill</h2>
<p>A critical observation emerges from the simulation: the standard deviation of scores under each system behaves differently as a function of player skill.</p>
<p>Under World Bowling, score standard deviation peaks at low-to-moderate skill levels (SD <span class="math inline">\(\approx\)</span> 28 at competitive level) and then <strong>decreases monotonically</strong> as skill increases, reaching SD <span class="math inline">\(\approx\)</span> 18.6 at the Top 10 level. This compression occurs because high-skill World Bowling games converge toward the maximum of 300 — with most frames scoring 30 (strike), the remaining variance comes only from occasional non-strikes.</p>
<p>Under traditional scoring, standard deviation increases with skill through the competitive range and remains elevated (SD <span class="math inline">\(\approx\)</span> 25.7 at professional, <span class="math inline">\(\approx\)</span> 24.4 at Top 10). This is because the compounding bonus structure amplifies the consequences of each non-strike — a single open frame in an otherwise perfect game costs substantially more under traditional scoring than under World Bowling, maintaining score spread even at elite levels.</p>
</section>
<section id="the-crossover-point" class="level2">
<h2 class="anchored" data-anchor-id="the-crossover-point">The Crossover Point</h2>
<p>We sweep strike rate continuously from 10% to 80% and compute score standard deviation under each system. The two curves cross at approximately <strong>50–51% strike rate</strong>. Below this threshold, World Bowling provides greater score spread; above it, traditional scoring provides greater spread.</p>
<p>This crossover has a direct competitive interpretation. At recreational and club levels, World Bowling’s wider score distribution means it actually provides <em>more</em> discrimination between adjacent skill levels — supporting the case for its use in casual and league play. At competitive and professional levels, the reversal means traditional scoring provides the finer discrimination that elite competition requires.</p>
<div id="fig-crossover" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-crossover-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<embed src="../figures/fig10_crossover_analysis.pdf" class="img-fluid" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-crossover-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Left: mean score <span class="math inline">\(\pm\)</span> 1 SD by strike rate under both systems. Right: score standard deviation as a function of strike rate, showing the crossover at approximately 51%.
</figcaption>
</figure>
</div>
</section>
<section id="between-tier-vs-within-tier-discrimination" class="level2">
<h2 class="anchored" data-anchor-id="between-tier-vs-within-tier-discrimination">Between-Tier vs Within-Tier Discrimination</h2>
<p>Our simulation reveals an important nuance. When comparing <em>between tiers</em> (e.g., recreational vs club), both scoring systems produce nearly identical Cohen’s <span class="math inline">\(d\)</span> effect sizes — ranging from 2.3 (recreational vs club) down to 0.6 (professional vs Top 10), but with the two systems matching to within 0.03 at every tier boundary. The choice of scoring system does not substantially affect the ability to distinguish a recreational player from a club player, or a club player from a competitive one.</p>
<p>The meaningful difference lies in <em>within-tier discrimination</em> — separating two players at the same general skill level who differ in their ability to sustain consecutive strikes. Consider two professional bowlers, both with approximately 70% strike rates, but one who tends to string strikes in runs of 4–5 and another who distributes them more evenly. Under traditional scoring, the streak bowler’s compounding bonuses produce measurably higher scores. Under World Bowling, their scores are statistically indistinguishable.</p>
</section>
</section>
<section id="professional-level-sequence-analysis" class="level1">
<h1>Professional-Level Sequence Analysis</h1>
<section id="specific-sequence-comparisons" class="level2">
<h2 class="anchored" data-anchor-id="specific-sequence-comparisons">Specific Sequence Comparisons</h2>
<p>To illustrate the practical consequences at the professional level, we compute scores for sequences representative of elite play:</p>
<div id="tbl-proseq" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-proseq-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: Professional-level sequence comparisons. The systems agree at the extremes but diverge substantially for mixed sequences.
</figcaption>
<div aria-describedby="tbl-proseq-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Sequence</th>
<th>Traditional</th>
<th>World Bowling</th>
<th>Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Perfect game (12 strikes)</td>
<td>300</td>
<td>300</td>
<td>0</td>
</tr>
<tr class="even">
<td>10 strikes + spare(7,3) + 7</td>
<td>287</td>
<td>300</td>
<td>−13</td>
</tr>
<tr class="odd">
<td>8 strikes + 2 spares(7,3) + 7</td>
<td>261</td>
<td>274</td>
<td>−13</td>
</tr>
<tr class="even">
<td>6 spares then 4 strikes + X,X</td>
<td>215</td>
<td>210</td>
<td>+5</td>
</tr>
<tr class="odd">
<td>4 strikes then 6 spares + 5</td>
<td>195</td>
<td>210</td>
<td>−15</td>
</tr>
<tr class="even">
<td>Alternating strike/spare × 5</td>
<td>200</td>
<td>225</td>
<td>−25</td>
</tr>
<tr class="odd">
<td>All spares (5,5) + 5</td>
<td>150</td>
<td>150</td>
<td>0</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Two patterns are notable. First, the systems agree at the extremes (perfect game and all spares) but diverge substantially for the mixed sequences that constitute the vast majority of professional games. Second, the <em>direction</em> of the difference depends on the sequence — traditional scoring rewards sequences with consecutive strikes more than World Bowling does, while World Bowling rewards isolated strikes more. The traditional system encodes <em>how</em> the strikes were arranged; World Bowling treats them as interchangeable.</p>
<div id="fig-proseq" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-proseq-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<embed src="../figures/fig11_professional_sequences.pdf" class="img-fluid" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-proseq-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Professional-level sequence comparison under both scoring systems.
</figcaption>
</figure>
</div>
</section>
<section id="the-fourth-to-fifth-strike-problem" class="level2">
<h2 class="anchored" data-anchor-id="the-fourth-to-fifth-strike-problem">The Fourth-to-Fifth Strike Problem</h2>
<p>Consider a professional bowler who has thrown four consecutive strikes. Under traditional scoring, the fifth strike is worth substantially more than under World Bowling (+21 from the compounding bonus structure), because it both earns its own bonus and retroactively increases the value of the preceding strikes. Under World Bowling, the fifth strike is worth exactly the same as if it were the first strike of the game (30 points, net +21 over an average open frame).</p>
<p>This flattening of the reward gradient at the professional level is not a simplification — it is a loss of information. The ability to extend a strike run from four to five frames is one of the most difficult and competitively meaningful feats in professional bowling. Traditional scoring encodes that difficulty in the score. World Bowling does not.</p>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<section id="what-scoring-systems-measure" class="level2">
<h2 class="anchored" data-anchor-id="what-scoring-systems-measure">What Scoring Systems Measure</h2>
<p>A scoring system is a function from a sequence of physical performances to a number. The properties of that function determine what the number communicates about the athlete’s skill — a perspective that connects to the broader theory of proper scoring rules, where the design of a measurement function determines whether it faithfully elicits the quantity it claims to measure <span class="citation" data-cites="gneiting2007">(<a href="#ref-gneiting2007" role="doc-biblioref">Gneiting &amp; Raftery, 2007</a>)</span>. Two scoring systems can agree on the maximum possible score (both systems peak at 300 for a perfect game) while disagreeing significantly on how they encode the path to that maximum.</p>
<p>Traditional bowling scoring encodes two distinct performance qualities simultaneously: the absolute pin count (how many pins were knocked down) and the sequencing of that performance (whether those knockdowns were concentrated in consecutive frames or distributed across the game). World Bowling scoring encodes only the first.</p>
</section>
<section id="the-commutativity-trade-off" class="level2">
<h2 class="anchored" data-anchor-id="the-commutativity-trade-off">The Commutativity Trade-off</h2>
<p>The commutativity of World Bowling scoring (Proposition 1) is its defining feature. It makes the system simple to compute and explain. But commutativity in a scoring function means that sustained performance is not valued above distributed performance. In most competitive sports, consecutive success is considered more difficult than the same success spread over time — a tennis player who wins six consecutive games demonstrates something different from one who wins six non-consecutive games. Traditional bowling scoring agrees with this intuition. World Bowling scoring does not.</p>
</section>
<section id="the-appropriate-domain-for-each-system" class="level2">
<h2 class="anchored" data-anchor-id="the-appropriate-domain-for-each-system">The Appropriate Domain for Each System</h2>
<p>We do not argue that current-frame scoring lacks merit. For recreational participants, its simplicity and accessibility represent genuine improvements over traditional scoring. The simulation results support this: below approximately 50% strike rate, World Bowling actually provides <em>greater</em> score spread, and its simpler computation removes a barrier to casual participation. The higher Shannon entropy of the World Bowling distribution (5.94 bits vs 5.81 bits for traditional; <span class="citation" data-cites="shannon1948">Shannon (<a href="#ref-shannon1948" role="doc-biblioref">1948</a>)</span>) reflects this: scores are more evenly spread across the range, meaning a casual player’s score more directly reflects their raw pin count without the amplifying effect of bonus compounding. Entropy-based discrimination metrics have been applied in other sporting contexts with similar interpretive value <span class="citation" data-cites="ausloos2023">(see <a href="#ref-ausloos2023" role="doc-biblioref">Ausloos, 2023</a> for a recent application in multi-stage cycling)</span>.</p>
<p>Our argument is narrower: at the competitive and professional levels — where strike rates exceed 50% and the ability to string consecutive strikes is the distinguishing skill — current-frame scoring’s commutativity property actively obscures the performance differences it should be measuring. The crossover point at approximately 50% strike rate provides a concrete, empirically grounded threshold for this distinction. It is worth noting that the sport’s most commercially successful broadcast era — ABC’s <em>Pro Bowlers Tour</em>, which aired for 36 consecutive seasons from 1962 to 1997 — used traditional scoring exclusively, suggesting that scoring complexity per se has not historically been a barrier to mainstream television appeal.</p>
</section>
<section id="score-compression-at-the-elite-level" class="level2">
<h2 class="anchored" data-anchor-id="score-compression-at-the-elite-level">Score Compression at the Elite Level</h2>
<p>The high-score compression shown in <a href="#tbl-compression" class="quarto-xref">Table&nbsp;2</a>, combined with the decreasing standard deviation under World Bowling at high skill levels (<a href="#fig-crossover" class="quarto-xref">Figure&nbsp;9</a>), has practical consequences for competitive bowling. At the Top 10 professional level, World Bowling’s score SD of 18.6 compared to traditional’s 24.4 means that World Bowling provides approximately 24% less score spread. At the professional tier more broadly (SD 21.4 vs 25.7), the gap is similar. When more distinct game sequences map to the same score, the score provides less information about which of two players performed better in any individual game.</p>
</section>
<section id="recency-bias-and-the-perception-of-unfairness" class="level2">
<h2 class="anchored" data-anchor-id="recency-bias-and-the-perception-of-unfairness">Recency Bias and the Perception of Unfairness</h2>
<p>A common informal argument against traditional scoring takes the following form: consider Player A, who throws a spare in frame 1 and then strikes for the remainder of the game, and Player B, who strikes from frame 1 but finishes with an open frame. Many observers intuitively feel Player A — who finished on a strong run — should score as well or better than Player B, who faltered at the end. Under traditional scoring, Player B scores higher, because the early strikes compound forward into subsequent strikes.</p>
<p>This intuition is an instance of <strong>recency bias</strong> — the cognitive tendency to weight recent events more heavily than earlier ones <span class="citation" data-cites="gilovich1985">(<a href="#ref-gilovich1985" role="doc-biblioref">Gilovich et al., 1985</a>)</span>. Traditional scoring does not correct for recency bias; it actively works against it, valuing the full sequence of the game from the first ball. The perception that this is unfair reflects a human cognitive bias rather than a deficiency in the scoring system. World Bowling scoring, by treating each frame independently, implicitly accommodates recency bias — but in doing so, it loses the ability to distinguish the player who sustained excellence throughout from the one who achieved the same pin count in a less demanding sequence. The hot hand literature — extensively reviewed by <span class="citation" data-cites="bareli2006">Bar-Eli et al. (<a href="#ref-bareli2006" role="doc-biblioref">2006</a>)</span> and investigated in bowling specifically by <span class="citation" data-cites="yaari2012">Yaari &amp; Eisenmann (<a href="#ref-yaari2012" role="doc-biblioref">2012</a>)</span> and <span class="citation" data-cites="dorseypalmateer2004">Dorsey-Palmateer &amp; Smith (<a href="#ref-dorseypalmateer2004" role="doc-biblioref">2004</a>)</span> — provides empirical evidence that streaks in bowling are not purely random, further supporting the argument that a scoring system should be sensitive to sequential performance.</p>
</section>
<section id="the-290299-gap-as-a-design-artefact" class="level2">
<h2 class="anchored" data-anchor-id="the-290299-gap-as-a-design-artefact">The 290–299 Gap as a Design Artefact</h2>
<p>The impossibility of World Bowling scores in the range 290–299 is mathematically unavoidable given the system’s design. It is a direct consequence of the discrete jump between the maximum achievable score with 9 strikes (289) and the minimum score with 10 strikes (300). This gap means that a bowler who throws nine strikes and one near-perfect spare cannot be scored above 289, while one who converts that spare to a tenth strike jumps directly to 300. The scoring cliff at the top of the range is not a feature of athletic performance — it is an artefact of linear frame independence.</p>
</section>
<section id="robustness-across-simulation-models" class="level2">
<h2 class="anchored" data-anchor-id="robustness-across-simulation-models">Robustness Across Simulation Models</h2>
<p>Our base simulation assumes frame-to-frame independence: each ball’s outcome depends only on the player’s fixed skill parameters, not on preceding results. This is deliberately conservative. The hot hand literature in bowling <span class="citation" data-cites="yaari2012 dorseypalmateer2004">(<a href="#ref-dorseypalmateer2004" role="doc-biblioref">Dorsey-Palmateer &amp; Smith, 2004</a>; <a href="#ref-yaari2012" role="doc-biblioref">Yaari &amp; Eisenmann, 2012</a>)</span> provides empirical evidence that consecutive strikes are positively correlated — a “momentum” or streakiness effect — which an independence model ignores.</p>
<p>To test the sensitivity of our conclusions to this assumption, we compare three simulation models of increasing realism: the independent base case, a simple momentum model (±5% strike probability shift after strikes/opens), and a first-order Markov chain with leave-dependent spare difficulty (Section 6.2). <a href="#fig-models" class="quarto-xref">Figure&nbsp;11</a> shows the SD gap (traditional minus World Bowling) across all six skill tiers under each model. Two observations are immediate. First, all three models agree on the <em>direction</em> of the effect at every tier: World Bowling provides more spread below competitive level, and traditional scoring provides more spread above it. The crossover point is robust to model choice. Second, the more realistic models produce <em>larger</em> gaps at the professional and Top 10 levels — the Markov model yields a traditional scoring advantage of +5.8 SD points at the Top 10 tier, compared to +4.1 under independence. The independence assumption is therefore conservative: any realistic model of sequential dependence amplifies the effect.</p>
<div id="fig-models" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<embed src="../figures/fig13_model_comparison.pdf" class="img-fluid" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: SD gap (Traditional minus World Bowling) across all six skill tiers under three simulation models: independent, momentum, and Markov chain with spare difficulty. More realistic models amplify the traditional scoring advantage at elite tiers.
</figcaption>
</figure>
</div>
<div id="fig-momentum" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-momentum-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<embed src="../figures/fig12_momentum_comparison.pdf" class="img-fluid" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-momentum-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: Left: score standard deviation under independent and momentum models. Right: the SD gap between systems widens under momentum at elite tiers.
</figcaption>
</figure>
</div>
</section>
<section id="limitations-and-future-work" class="level2">
<h2 class="anchored" data-anchor-id="limitations-and-future-work">Limitations and Future Work</h2>
<p>This paper has several limitations that suggest directions for future work. First, the simulation uses a parametric skill model rather than real game data. Validating the results against a database of actual PBA tournament scores — applying both scoring systems to the same ball sequences — would provide a powerful empirical anchor. Second, while the Markov chain model captures first-order sequential dependence, more sophisticated models incorporating fatigue, lane oil breakdown, and frame-specific strategy could further refine the magnitude estimates. Third, our analysis focuses on individual game scores; extending to multi-game series and tournament formats would address whether the discrimination differences compound over longer competitions. Fourth, a formal Win Probability Added (WPA) analysis — computing how each scoring system affects the probability of winning a head-to-head match at each game state — would complement the present score-distribution analysis with a competition-dynamics perspective. The source code accompanying this paper is designed to support these extensions.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>We have demonstrated, through exact combinatorial analysis and skill-weighted simulation, that traditional and World Bowling scoring systems differ in mathematically precise and practically significant ways:</p>
<ol type="1">
<li><p><strong>Traditional scoring is sequence-sensitive.</strong> The order of frames matters, and it matters in a way that rewards consecutive success. World Bowling scoring is commutative — order is irrelevant. Exhaustive permutation analysis shows that the same frame composition can produce a score range of up to 39 points under traditional scoring, while World Bowling collapses all orderings to a single score.</p></li>
<li><p><strong>Traditional scoring has a compounding reward gradient for consecutive strikes.</strong> Each strike in a string is worth more than an isolated strike, creating a non-linear incentive for sustained excellence. World Bowling scoring is linear — every strike is worth the same regardless of context.</p></li>
<li><p><strong>The scoring systems’ discriminating power crosses over at approximately 50% strike rate.</strong> Below this threshold, World Bowling’s wider score distribution provides adequate discrimination and its simplicity is a net benefit. Above it, traditional scoring provides substantially greater score spread — over 30% more at the Top 10 professional level — precisely where discrimination matters most.</p></li>
<li><p><strong>The distinction matters most within skill tiers, not between them.</strong> Both systems adequately separate recreational players from professionals. The critical difference is in separating two elite players who differ in their ability to sustain consecutive strikes — the skill that defines professional bowling.</p></li>
</ol>
<p>The complexity of traditional scoring is not an accident of history. It is the mechanism by which the system encodes the quality most distinctive about elite bowling: the ability to string consecutive strikes across frames and across games. Removing that complexity removes that measurement.</p>
<p>For governing bodies, tournament organisers, and league administrators, the practical implication is straightforward: current-frame scoring is appropriate for recreational participation and casual leagues, where its simplicity removes a genuine barrier to entry. It is not appropriate for professional and elite competition, where the scoring system’s role is to measure and distinguish sustained skill — and where the crossover point identified in this paper places competitive bowlers firmly in the domain where traditional scoring provides superior discrimination.</p>
</section>
<section id="reproducibility" class="level1 unnumbered">
<h1 class="unnumbered">Reproducibility</h1>
<p>All results in this paper are fully reproducible. The source code, exact distribution data, and analysis scripts are publicly available at <a href="https://github.com/michael-borck/skill-sequence-scoring" class="uri">https://github.com/michael-borck/skill-sequence-scoring</a>. An interactive companion website at <a href="https://michael-borck.github.io/skill-sequence-scoring" class="uri">https://michael-borck.github.io/skill-sequence-scoring</a> allows readers to explore the sequence sensitivity and reward gradient results directly.</p>
</section>
<section id="acknowledgements" class="level1 unnumbered">
<h1 class="unnumbered">Acknowledgements</h1>
<p>All computations were performed in Python using NumPy, Matplotlib, and SciPy. The manuscript was prepared with Quarto and rendered via LuaLaTeX. Score distribution computations were verified against published tables by Balmoral Software.</p>
<p>AI-assisted tools (Anthropic Claude, GitHub Copilot, Google Gemini) were used during code development, manuscript drafting, and critical review. All mathematical results, research design, arguments, and editorial decisions are the author’s own.</p>
</section>
<section id="references" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-ausloos2023" class="csl-entry" role="listitem">
Ausloos, M. (2023). Shannon entropy and <span>Herfindahl-Hirschman</span> index as team performance indicators in cyclist multi-stage races. <em>Entropy</em>, <em>25</em>(6), 955. <a href="https://doi.org/10.3390/e25060955">https://doi.org/10.3390/e25060955</a>
</div>
<div id="ref-balmoral" class="csl-entry" role="listitem">
Balmoral Software. (2019). <em>All about bowling scores</em>. <a href="http://www.balmoralsoftware.com/bowling/bowling.htm" class="uri">http://www.balmoralsoftware.com/bowling/bowling.htm</a>.
</div>
<div id="ref-bareli2006" class="csl-entry" role="listitem">
Bar-Eli, M., Avugos, S., &amp; Raab, M. (2006). Twenty years of <span>“hot hand”</span> research: Review and critique. <em>Psychology of Sport and Exercise</em>, <em>7</em>(6), 525–553. <a href="https://doi.org/10.1016/j.psychsport.2006.03.001">https://doi.org/10.1016/j.psychsport.2006.03.001</a>
</div>
<div id="ref-cooper1990" class="csl-entry" role="listitem">
Cooper, C. N., &amp; Kennedy, R. E. (1990). A generating function for the distribution of the scores of all possible bowling games. <em>Mathematics Magazine</em>, <em>63</em>(4), 239–243. <a href="https://doi.org/10.1080/0025570X.1990.11977527">https://doi.org/10.1080/0025570X.1990.11977527</a>
</div>
<div id="ref-dorseypalmateer2004" class="csl-entry" role="listitem">
Dorsey-Palmateer, R., &amp; Smith, G. (2004). Bowlers’ hot hands. <em>The American Statistician</em>, <em>58</em>(1), 38–45. <a href="https://doi.org/10.1198/0003130042809">https://doi.org/10.1198/0003130042809</a>
</div>
<div id="ref-gilovich1985" class="csl-entry" role="listitem">
Gilovich, T., Vallone, R., &amp; Tversky, A. (1985). The hot hand in basketball: On the misperception of random sequences. <em>Cognitive Psychology</em>, <em>17</em>(3), 295–314. <a href="https://doi.org/10.1016/0010-0285(85)90010-6">https://doi.org/10.1016/0010-0285(85)90010-6</a>
</div>
<div id="ref-gneiting2007" class="csl-entry" role="listitem">
Gneiting, T., &amp; Raftery, A. E. (2007). Strictly proper scoring rules, prediction, and estimation. <em>Journal of the American Statistical Association</em>, <em>102</em>(477), 359–378. <a href="https://doi.org/10.1198/016214506000001437">https://doi.org/10.1198/016214506000001437</a>
</div>
<div id="ref-hohn2009" class="csl-entry" role="listitem">
Hohn, J. L. (2009). <em>Generalized probabilistic bowling distributions</em> [Master’s thesis]. Western Kentucky University.
</div>
<div id="ref-insidethegames2014" class="csl-entry" role="listitem">
Inside The Games. (2014). <em>New scoring system introduced for <span>World Bowling Tour</span> finals to try to help sport’s <span>Olympic</span> ambitions</em>. <a href="https://www.insidethegames.biz/articles/new-scoring-system-introduced-for-world-bowling-tour-finals-to-try-to-help-sports-olympic-ambitions" class="uri">https://www.insidethegames.biz/articles/new-scoring-system-introduced-for-world-bowling-tour-finals-to-try-to-help-sports-olympic-ambitions</a>.
</div>
<div id="ref-keogh2011" class="csl-entry" role="listitem">
Keogh, J., &amp; O’Neill, S. (2011). <em>A statistical analysis of 10-pin bowling scores and an examination of the fairness of alternative handicapping systems</em>. National University of Ireland, Maynooth.
</div>
<div id="ref-martin2006" class="csl-entry" role="listitem">
Martin, D. E. (2006). Hot-hand effects in sports and a recursive method of computing probabilities for streaks. <em>Computers and Operations Research</em>, <em>33</em>, 1983–2001. <a href="https://doi.org/10.1016/j.cor.2004.09.016">https://doi.org/10.1016/j.cor.2004.09.016</a>
</div>
<div id="ref-mccarthy2011" class="csl-entry" role="listitem">
McCarthy, D. (2011). Estimating different sources of variation and predicting tournament outcomes in professional bowling. <em>Chance</em>, <em>24</em>(3), 37–46. <a href="https://doi.org/10.1080/09332480.2011.10739870">https://doi.org/10.1080/09332480.2011.10739870</a>
</div>
<div id="ref-reuters2025wbl" class="csl-entry" role="listitem">
Reuters. (2025). <em>Exclusive: <span>Betts</span>-backed <span>World Bowling League</span> to roll out next year</em>. <a href="https://www.reuters.com" class="uri">https://www.reuters.com</a>.
</div>
<div id="ref-shannon1948" class="csl-entry" role="listitem">
Shannon, C. E. (1948). A mathematical theory of communication. <em>Bell System Technical Journal</em>, <em>27</em>(3), 379–423. <a href="https://doi.org/10.1002/j.1538-7305.1948.tb01338.x">https://doi.org/10.1002/j.1538-7305.1948.tb01338.x</a>
</div>
<div id="ref-vanderwerken2018" class="csl-entry" role="listitem">
VanDerwerken, D. N., &amp; Kenter, F. H. J. (2018). A generative <span>Markov</span> model for bowling scores. <em>Journal of Quantitative Analysis in Sports</em>, <em>14</em>(4), 213–226. <a href="https://doi.org/10.1515/jqas-2018-0064">https://doi.org/10.1515/jqas-2018-0064</a>
</div>
<div id="ref-worldbowling2014" class="csl-entry" role="listitem">
World Bowling. (2014). <em>World bowling scoring system</em>. <a href="http://www.worldbowling.org" class="uri">http://www.worldbowling.org</a>.
</div>
<div id="ref-yaari2012" class="csl-entry" role="listitem">
Yaari, G., &amp; Eisenmann, S. (2012). Hot hand on strike: Bowling data indicates correlation to recent past results, not causality. <em>PLOS ONE</em>, <em>7</em>(1), e30112. <a href="https://doi.org/10.1371/journal.pone.0030112">https://doi.org/10.1371/journal.pone.0030112</a>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>